import { useMemo, useState } from "react";
import { Mail, Pencil, Plus, Search, UserCheck, UserX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PageHeader } from "@/components/bhurakshak/page-header";
import { EmptyState } from "@/components/bhurakshak/feedback-state";
import { audits, users as initialUsers } from "@/data/mock-data";
import type { AppUser, UserRole } from "@/types/land-record";
import { toast } from "sonner";

export function AuditPage() {
  const [query, setQuery] = useState(""); const [action, setAction] = useState("all");
  const items = useMemo(() => audits.filter((a) => (action === "all" || a.action === action) && [a.recordId, a.user, a.detail].join(" ").toLowerCase().includes(query.toLowerCase())), [query, action]);
  return <div className="space-y-7"><PageHeader eyebrow="Transparency" title="Audit log" description="A chronological view of record creation, correction, submission, approval, and rejection activity."/><div className="grid gap-3 border border-border bg-card p-4 sm:grid-cols-[minmax(0,1fr)_200px]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search records or officers…"/></div><Select value={action} onValueChange={setAction}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All actions</SelectItem>{["Created", "Edited", "Submitted", "Approved", "Rejected"].map((a) => <SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent></Select></div>{items.length ? <div className="border border-border bg-card"><div className="hidden grid-cols-[140px_140px_180px_minmax(0,1fr)] border-b border-border bg-muted px-5 py-3 text-[10px] uppercase tracking-widest text-muted-foreground md:grid"><span>Time</span><span>Action</span><span>User</span><span>Change</span></div>{items.map((event) => <div key={event.id} className="grid gap-2 border-b border-border px-5 py-4 last:border-0 md:grid-cols-[140px_140px_180px_minmax(0,1fr)]"><p className="font-mono text-[10px] text-muted-foreground">{event.timestamp}</p><div><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-medium">{event.action}</span><p className="mt-2 font-mono text-[10px] text-muted-foreground">{event.recordId}</p></div><div><p className="text-sm font-medium">{event.user}</p><p className="text-[10px] text-muted-foreground">{event.role}</p></div><div><p className="text-sm">{event.detail}</p>{event.oldValue && <p className="mt-2 text-xs"><span className="text-destructive line-through">{event.oldValue}</span><span className="mx-2">→</span><span className="text-success">{event.newValue}</span></p>}</div></div>)}</div> : <EmptyState/>}</div>;
}

export function UsersPage() {
  const [people, setPeople] = useState(initialUsers); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState<UserRole>("officer");
  const invite = () => { if (!name.trim() || !email.includes("@")) return toast.error("Enter a valid name and email"); const person: AppUser = { id: `U-${Date.now()}`, name, email, role, district: "Bareilly", active: true, lastActive: "Invited" }; setPeople((items) => [person, ...items]); setOpen(false); setName(""); setEmail(""); toast.success("Mock invitation added"); };
  return <div className="space-y-7"><PageHeader eyebrow="Administration" title="User control" description="Manage frontend demo roles and account status for district personnel." actions={<Button onClick={() => setOpen(true)}><Plus/> Invite user</Button>}/><div className="overflow-x-auto border border-border bg-card"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-muted text-[10px] uppercase tracking-widest text-muted-foreground"><tr><th className="px-4 py-3">User</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">District</th><th className="px-4 py-3">Last active</th><th className="px-4 py-3">Access</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-border">{people.map((person) => <tr key={person.id}><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-primary-soft text-xs font-semibold text-primary">{person.name.split(" ").map((p) => p[0]).slice(0,2).join("")}</div><div><p className="font-medium">{person.name}</p><p className="text-xs text-muted-foreground">{person.email}</p></div></div></td><td className="px-4 py-4 capitalize">{person.role}</td><td className="px-4 py-4">{person.district}</td><td className="px-4 py-4 text-muted-foreground">{person.lastActive}</td><td className="px-4 py-4"><div className="flex items-center gap-2">{person.active ? <UserCheck className="size-4 text-success"/> : <UserX className="size-4 text-destructive"/>}<Switch checked={person.active} onCheckedChange={(checked) => setPeople((list) => list.map((item) => item.id === person.id ? { ...item, active: checked } : item))} aria-label={`Toggle ${person.name} access`}/></div></td><td className="px-4 py-4"><Button variant="ghost" size="icon" aria-label={`Edit ${person.name}`} onClick={() => toast.info("Role editor is ready for API integration")}><Pencil/></Button></td></tr>)}</tbody></table></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Invite district user</DialogTitle><DialogDescription>This creates a frontend-only sample account; no email will be sent.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label htmlFor="invite-name">Full name</Label><Input id="invite-name" value={name} onChange={(e) => setName(e.target.value)} className="mt-2"/></div><div><Label htmlFor="invite-email">Government email</Label><Input id="invite-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2"/></div><div><Label>Role</Label><Select value={role} onValueChange={(value) => setRole(value as UserRole)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="officer">Officer</SelectItem><SelectItem value="supervisor">Supervisor</SelectItem><SelectItem value="admin">Administrator</SelectItem></SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={invite}><Mail/> Send mock invite</Button></DialogFooter></DialogContent></Dialog></div>;
}

export function ProfilePage() {
  const [saved, setSaved] = useState(false); const [notifications, setNotifications] = useState(true);
  return <div className="mx-auto max-w-3xl space-y-7"><PageHeader eyebrow="Account" title="Profile & preferences" description="Update the details used in the frontend demonstration."/><section className="border border-border bg-card"><div className="flex items-center gap-4 border-b border-border p-6"><div className="grid size-14 place-items-center rounded-full bg-primary-soft text-lg font-semibold text-primary">RK</div><div><h2 className="font-semibold">Rajesh Kumar</h2><p className="text-sm text-muted-foreground">District Administrator · Bareilly</p></div></div><div className="grid gap-5 p-6 sm:grid-cols-2"><div><Label htmlFor="full-name">Full name</Label><Input id="full-name" defaultValue="Rajesh Kumar" className="mt-2"/></div><div><Label htmlFor="email">Government email</Label><Input id="email" defaultValue="rajesh.kumar@gov.in" className="mt-2"/></div><div><Label htmlFor="district-profile">Assigned district</Label><Input id="district-profile" defaultValue="Bareilly" className="mt-2" disabled/></div><div><Label htmlFor="role-profile">Role</Label><Input id="role-profile" defaultValue="Administrator" className="mt-2" disabled/></div></div><div className="flex items-center justify-between border-t border-border p-6"><div><p className="text-sm font-medium">Review notifications</p><p className="text-xs text-muted-foreground">Receive alerts for high-priority records.</p></div><Switch checked={notifications} onCheckedChange={setNotifications}/></div><div className="flex justify-end border-t border-border p-6"><Button onClick={() => { setSaved(true); toast.success("Profile saved locally"); }}>{saved ? "Saved" : "Save changes"}</Button></div></section></div>;
}
