import { Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, Download, FileStack, ShieldAlert, TrendingUp } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/bhurakshak/page-header";
import { StatusBadge } from "@/components/bhurakshak/status-badge";
import { monthlyProgress, records, villageIssues } from "@/data/mock-data";
import districtMap from "@/assets/district-coverage.jpg";
import { toast } from "sonner";

const metrics = [
  { label: "Documents processed", value: "14,208", detail: "+12.4% this month", icon: FileStack, tone: "text-primary" },
  { label: "Verified records", value: "12,016", detail: "84.6% completion", icon: CheckCircle2, tone: "text-success" },
  { label: "Pending review", value: "1,402", detail: "98 due today", icon: Clock3, tone: "text-info" },
  { label: "Flagged", value: "182", detail: "36 high priority", icon: ShieldAlert, tone: "text-destructive" },
];
export function DashboardPage() {
  return <div className="space-y-8"><PageHeader eyebrow="Bareilly district" title="Digitization overview" description="Track land-record processing, verification quality, and review backlogs across the district." actions={<Button variant="outline" onClick={() => toast.success("Progress report prepared for download")}><Download/> Export report</Button>}/>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => <article key={metric.label} className="border border-border bg-card p-5"><div className="flex items-start justify-between"><p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{metric.label}</p><metric.icon className={`size-4 ${metric.tone}`}/></div><p className="mt-4 text-3xl font-semibold">{metric.value}</p><p className="mt-1 text-xs text-muted-foreground">{metric.detail}</p></article>)}</section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,.75fr)]"><div className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-semibold">Processing progress</h2><p className="mt-1 text-xs text-muted-foreground">Documents processed and verified in the last six months</p></div><TrendingUp className="size-5 text-primary"/></div><div className="h-72 p-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthlyProgress}><defs><linearGradient id="processed" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--primary)" stopOpacity={0.22}/><stop offset="95%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month" tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false}/><YAxis tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ border: "1px solid var(--border)", borderRadius: 4, background: "var(--popover)" }}/><Area type="monotone" dataKey="processed" stroke="var(--primary)" fill="url(#processed)" strokeWidth={2}/><Area type="monotone" dataKey="verified" stroke="var(--chart-2)" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>
      <div className="border border-border bg-card"><div className="border-b border-border p-5"><h2 className="font-semibold">District coverage</h2><p className="mt-1 text-xs text-muted-foreground">Village parcel digitization status</p></div><img src={districtMap} alt="Illustrated cadastral coverage map of Bareilly district" loading="lazy" width={944} height={704} className="aspect-[4/3] w-full object-cover"/><div className="grid grid-cols-2 border-t border-border text-center"><div className="p-3"><p className="text-lg font-semibold">84.2%</p><p className="text-[10px] uppercase text-muted-foreground">Coverage</p></div><div className="border-l border-border p-3"><p className="text-lg font-semibold">42 / 58</p><p className="text-[10px] uppercase text-muted-foreground">Villages</p></div></div></div></section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.85fr)]"><div><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Recent records</h2><Button asChild variant="link"><Link to="/records">View all <ArrowRight/></Link></Button></div><div className="overflow-x-auto border border-border bg-card"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-muted text-[10px] uppercase tracking-widest text-muted-foreground"><tr><th className="px-4 py-3">Record ID</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Village</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-border">{records.slice(0,5).map((record) => <tr key={record.id} className="hover:bg-muted/50"><td className="px-4 py-3 font-mono text-xs">{record.id}</td><td className="px-4 py-3 font-medium">{record.ownerName}</td><td className="px-4 py-3 text-muted-foreground">{record.village}</td><td className="px-4 py-3"><StatusBadge status={record.status}/></td><td className="px-4 py-3">{record.confidence}%</td><td className="px-4 py-3"><Link to="/records/$recordId" params={{ recordId: record.id }} className="text-xs font-medium text-primary">Open</Link></td></tr>)}</tbody></table></div></div>
      <div><h2 className="mb-4 text-lg font-semibold">Village validation health</h2><div className="divide-y divide-border border border-border bg-card">{villageIssues.map((item) => <div key={item.village} className="p-4"><div className="flex justify-between text-sm"><span className="font-medium">{item.village}</span><span className="text-muted-foreground">{item.issues} issues</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${item.accuracy}%` }}/></div><p className="mt-2 text-[11px] text-muted-foreground">{item.accuracy}% validation accuracy · {item.processed} processed</p></div>)}</div><div className="mt-4 flex gap-3 border border-warning/20 bg-warning-soft p-4"><AlertTriangle className="size-5 shrink-0 text-warning-foreground"/><div><p className="text-sm font-medium">Sonapur needs attention</p><p className="mt-1 text-xs text-muted-foreground">Duplicate survey numbers account for 62% of open issues.</p></div></div></div></section>
  </div>;
}
