import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { CheckCircle2, ChevronLeft, ChevronRight, Eye, Filter, Search, ShieldAlert, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PageHeader } from "@/components/bhurakshak/page-header";
import { EmptyState } from "@/components/bhurakshak/feedback-state";
import { SeverityBadge, StatusBadge } from "@/components/bhurakshak/status-badge";
import { audits, records } from "@/data/mock-data";
import sampleDocument from "@/assets/sample-land-record.jpg";
import { toast } from "sonner";

export function RecordsPage({ flagged = false }: { flagged?: boolean }) {
  const [query, setQuery] = useState(""); const [village, setVillage] = useState("all"); const [page, setPage] = useState(1);
  const visible = useMemo(() => records.filter((r) => (!flagged || r.status === "flagged") && (village === "all" || r.village === village) && [r.ownerName, r.surveyNumber, r.khataNumber, r.village, r.id].join(" ").toLowerCase().includes(query.toLowerCase())), [query, village, flagged]);
  return <div className="space-y-7"><PageHeader eyebrow={flagged ? "Supervisor workspace" : "Verified registry"} title={flagged ? "Flagged records" : "Search land records"} description={flagged ? "Review records that failed automated validation and require a supervisor decision." : "Search by owner, survey number, khata number, village, or record ID."}/>
    <div className="grid gap-3 border border-border bg-card p-4 sm:grid-cols-[minmax(0,1fr)_200px_auto]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search owner, survey, khata, village…" className="pl-9"/></div><Select value={village} onValueChange={setVillage}><SelectTrigger><SelectValue placeholder="All villages"/></SelectTrigger><SelectContent><SelectItem value="all">All villages</SelectItem>{[...new Set(records.map((r) => r.village))].map((name) => <SelectItem value={name} key={name}>{name}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={() => { setQuery(""); setVillage("all"); }}><Filter/> Reset</Button></div>
    {visible.length ? <div className="overflow-x-auto border border-border bg-card"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-muted text-[10px] uppercase tracking-widest text-muted-foreground"><tr><th className="px-4 py-3">Record</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Survey / Khata</th><th className="px-4 py-3">Village</th>{flagged && <th className="px-4 py-3">Issue</th>}<th className="px-4 py-3">Status</th><th className="px-4 py-3">Updated</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-border">{visible.map((record) => <tr key={record.id} className="hover:bg-muted/40"><td className="px-4 py-4 font-mono text-xs">{record.id}</td><td className="px-4 py-4 font-medium">{record.ownerName}</td><td className="px-4 py-4"><p>{record.surveyNumber}</p><p className="text-xs text-muted-foreground">Khata {record.khataNumber}</p></td><td className="px-4 py-4">{record.village}</td>{flagged && <td className="max-w-xs px-4 py-4"><div className="flex items-start gap-2">{record.severity && <SeverityBadge severity={record.severity}/>}<span className="text-xs text-muted-foreground">{record.issue}</span></div></td>}<td className="px-4 py-4"><StatusBadge status={record.status}/></td><td className="px-4 py-4 text-xs text-muted-foreground">{record.updatedAt}</td><td className="px-4 py-4"><Button asChild variant="ghost" size="sm"><Link to="/records/$recordId" params={{ recordId: record.id }}><Eye/> Review</Link></Button></td></tr>)}</tbody></table></div> : <EmptyState action={() => { setQuery(""); setVillage("all"); }}/>}<div className="flex items-center justify-between text-xs text-muted-foreground"><span>Showing {visible.length} of {flagged ? 2 : records.length} records</span><div className="flex items-center gap-2"><Button variant="outline" size="icon" disabled={page === 1} onClick={() => setPage(1)} aria-label="Previous page"><ChevronLeft/></Button><span>Page {page} of 1</span><Button variant="outline" size="icon" disabled aria-label="Next page"><ChevronRight/></Button></div></div>
  </div>;
}

export function RecordDetailPage({ recordId }: { recordId: string }) {
  const record = records.find((r) => r.id === recordId) ?? records[1]; const [dialog, setDialog] = useState<"approve" | "reject" | null>(null); const [comment, setComment] = useState(""); const [decision, setDecision] = useState<string | null>(null);
  const fields = [["Owner name", record.ownerName], ["Survey number", record.surveyNumber], ["Khasra number", record.khasraNumber], ["Khata number", record.khataNumber], ["Village", record.village], ["Tehsil", record.tehsil], ["District", record.district], ["Plot area", `${record.plotArea} hectares`], ["Classification", record.landClassification]];
  const confirm = () => { if (dialog === "reject" && !comment.trim()) return toast.error("Add a rejection comment"); const label = dialog === "approve" ? "Approved by supervisor" : "Returned to officer"; setDecision(label); setDialog(null); toast.success(label); };
  return <div className="space-y-6"><PageHeader eyebrow={`Record detail · ${record.id}`} title={record.ownerName} description={`${record.village}, ${record.tehsil}, ${record.district}`} actions={<div className="flex gap-2"><Button variant="outline" onClick={() => setDialog("reject")}><XCircle/> Reject</Button><Button onClick={() => setDialog("approve")}><CheckCircle2/> Approve override</Button></div>}/>{decision && <div className="border border-success/20 bg-success-soft p-4 text-sm font-medium text-success">{decision} · This is a frontend-only demonstration.</div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(320px,.75fr)_minmax(0,1.25fr)]"><section className="border border-border bg-card"><div className="border-b border-border p-4"><h2 className="font-semibold">Original scan</h2></div><div className="bg-document p-5"><img src={sampleDocument} alt="Sample land record scan" loading="lazy" width={800} height={1200} className="mx-auto max-h-[680px] w-auto shadow-document"/></div></section><div className="space-y-6"><section className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5"><h2 className="font-semibold">Structured record</h2><StatusBadge status={record.status}/></div><dl className="grid sm:grid-cols-2">{fields.map(([label, value]) => <div key={label} className="border-b border-border p-4 odd:sm:border-r"><dt className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>)}</dl></section>{record.issue && <section className="border border-destructive/20 bg-danger-soft p-5"><div className="flex gap-3"><ShieldAlert className="size-5 shrink-0 text-destructive"/><div><div className="flex items-center gap-2"><h2 className="font-semibold">Validation failed</h2>{record.severity && <SeverityBadge severity={record.severity}/>}</div><p className="mt-2 text-sm text-muted-foreground">{record.issue}</p><p className="mt-3 text-xs">Rule: duplicate_survey_number · Unresolved</p></div></div></section>}<section className="border border-border bg-card p-5"><h2 className="font-semibold">Audit history</h2><div className="mt-5 space-y-5">{audits.filter((a) => a.recordId === record.id).map((event) => <div key={event.id} className="grid grid-cols-[12px_minmax(0,1fr)] gap-3"><span className="mt-1 size-2 rounded-full bg-primary"/><div><p className="text-sm font-medium">{event.action} · {event.user}</p><p className="mt-1 text-xs text-muted-foreground">{event.detail}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{event.timestamp}</p></div></div>)}</div></section></div></div>
    <Dialog open={dialog !== null} onOpenChange={(open) => !open && setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{dialog === "approve" ? "Approve flagged record?" : "Return record to officer?"}</DialogTitle><DialogDescription>{dialog === "approve" ? "This override marks the record verified despite the validation warning." : "Explain what must be corrected before the record can be submitted again."}</DialogDescription></DialogHeader><Textarea value={comment} onChange={(e) => setComment(e.target.value)} placeholder={dialog === "approve" ? "Optional supervisor note" : "Required correction note"}/><DialogFooter><Button variant="outline" onClick={() => setDialog(null)}>Cancel</Button><Button variant={dialog === "reject" ? "destructive" : "default"} onClick={confirm}>{dialog === "approve" ? "Confirm approval" : "Return record"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
