import { useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { AlertCircle, CheckCircle2, FileImage, FileText, LoaderCircle, RotateCcw, ScanLine, UploadCloud, ZoomIn, ZoomOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageHeader } from "@/components/bhurakshak/page-header";
import { mockUpload } from "@/services/mock-api";
import sampleDocument from "@/assets/sample-land-record.jpg";
import { toast } from "sonner";

export function UploadPage() {
  const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [progress, setProgress] = useState(0); const [done, setDone] = useState(false); const [dragging, setDragging] = useState(false);
  const choose = (picked?: File) => { if (!picked) return; if (!/image|pdf/.test(picked.type)) return toast.error("Choose a JPG, PNG, TIFF, or PDF file"); if (picked.size > 15 * 1024 * 1024) return toast.error("File must be smaller than 15 MB"); setFile(picked); setDone(false); };
  const submit = async () => { if (!file) return toast.error("Add a document before continuing"); setProgress(18); const timer = setInterval(() => setProgress((value) => Math.min(value + 14, 88)), 180); await mockUpload(); clearInterval(timer); setProgress(100); setDone(true); toast.success("Document uploaded and mock extraction completed"); };
  return <div className="space-y-8"><PageHeader eyebrow="Digitization workflow" title="Upload land document" description="Add one scanned record and its location details. The demo will simulate OCR extraction without sending the file anywhere."/>
    <div className="grid gap-8 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)]"><section className="space-y-6"><div onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); choose(event.dataTransfer.files[0]); }} className={`grid min-h-72 place-items-center border-2 border-dashed p-8 text-center transition-colors ${dragging ? "border-primary bg-primary-soft" : "border-border bg-card"}`}><input ref={inputRef} type="file" accept="image/*,.pdf" className="hidden" onChange={(event) => choose(event.target.files?.[0])}/>{file ? <div><FileImage className="mx-auto size-10 text-primary"/><p className="mt-4 font-medium">{file.name}</p><p className="mt-1 text-xs text-muted-foreground">{(file.size / 1024 / 1024).toFixed(2)} MB · Ready to upload</p><Button variant="outline" size="sm" className="mt-5" onClick={() => inputRef.current?.click()}>Replace file</Button></div> : <div><UploadCloud className="mx-auto size-10 text-primary"/><h2 className="mt-4 font-semibold">Drop a scan here</h2><p className="mt-1 text-sm text-muted-foreground">JPG, PNG, TIFF or PDF · Maximum 15 MB</p><Button className="mt-5" onClick={() => inputRef.current?.click()}>Browse files</Button></div>}</div>{progress > 0 && <div className="border border-border bg-card p-5"><div className="flex justify-between text-sm"><span>{done ? "Extraction complete" : "Simulating document processing…"}</span><span className="font-medium">{progress}%</span></div><Progress value={progress} className="mt-3"/>{done && <div className="mt-4 flex items-center gap-2 text-sm text-success"><CheckCircle2 className="size-4"/> Nine fields extracted. Two need review.</div>}</div>}</section>
      <section className="border border-border bg-card p-6"><h2 className="font-semibold">Record location</h2><p className="mt-1 text-xs text-muted-foreground">Required for village-level validation.</p><div className="mt-6 space-y-5"><div><Label htmlFor="district">District</Label><Select defaultValue="bareilly"><SelectTrigger id="district" className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="bareilly">Bareilly</SelectItem><SelectItem value="lucknow">Lucknow</SelectItem><SelectItem value="prayagraj">Prayagraj</SelectItem></SelectContent></Select></div><div><Label htmlFor="tehsil">Tehsil</Label><Select defaultValue="fatehganj"><SelectTrigger id="tehsil" className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="fatehganj">Fatehganj</SelectItem><SelectItem value="aonla">Aonla</SelectItem><SelectItem value="baheri">Baheri</SelectItem></SelectContent></Select></div><div><Label htmlFor="village">Village</Label><Input id="village" defaultValue="Sonapur" className="mt-2"/></div><div><Label htmlFor="type">Document type</Label><Select defaultValue="khasra"><SelectTrigger id="type" className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="khasra">Khasra record</SelectItem><SelectItem value="khatauni">Khatauni</SelectItem><SelectItem value="deed">Sale deed</SelectItem><SelectItem value="map">Cadastral map</SelectItem></SelectContent></Select></div><Button className="w-full" onClick={submit} disabled={!file || (progress > 0 && !done)}>{progress > 0 && !done ? <LoaderCircle className="animate-spin"/> : <ScanLine/>} Start extraction</Button>{done && <Button asChild variant="outline" className="w-full"><Link to="/review/BR-2026-1043">Review extracted fields</Link></Button>}</div></section></div>
  </div>;
}

const initialFields = [
  { key: "owner", label: "Primary owner name", value: "Ram Lal Gangaram", confidence: 66 }, { key: "survey", label: "Survey number", value: "278/1", confidence: 98 },
  { key: "khasra", label: "Khasra number", value: "278", confidence: 96 }, { key: "khata", label: "Khata number", value: "45", confidence: 93 },
  { key: "village", label: "Village", value: "Sonapur", confidence: 91 }, { key: "tehsil", label: "Tehsil", value: "Fatehganj", confidence: 89 },
  { key: "district", label: "District", value: "Bareilly", confidence: 97 }, { key: "area", label: "Plot area (hectares)", value: "0.632", confidence: 72 },
];
export function ReviewPage() {
  const [fields, setFields] = useState(initialFields); const [zoom, setZoom] = useState(80); const [submitted, setSubmitted] = useState(false);
  return <div className="space-y-6"><PageHeader eyebrow="OCR review · BR-2026-1043" title="Verify extracted fields" description="Compare each field with the original scan. Amber fields need a manual check before submission." actions={<div className="flex gap-2"><Button variant="outline" onClick={() => setFields(initialFields)}><RotateCcw/> Reset</Button><Button onClick={() => { setSubmitted(true); toast.success("Record submitted for validation"); }} disabled={submitted}><CheckCircle2/> {submitted ? "Submitted" : "Submit for validation"}</Button></div>}/>
    {submitted && <div className="flex items-center gap-3 border border-success/20 bg-success-soft p-4 text-sm text-success"><CheckCircle2 className="size-5"/><div><p className="font-medium">Record submitted successfully</p><p className="text-xs">The mock validator found no mandatory-field errors.</p></div></div>}
    <div className="grid gap-6 xl:grid-cols-2"><section className="flex min-h-[700px] flex-col border border-border bg-card"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center border-b border-border px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium">Sonapur_Khasra_1973_scan.jpg</p><p className="text-[11px] text-muted-foreground">Original scanned document</p></div><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => setZoom((z) => Math.max(50, z - 10))} aria-label="Zoom out"><ZoomOut/></Button><span className="grid w-12 place-items-center text-xs">{zoom}%</span><Button variant="ghost" size="icon" onClick={() => setZoom((z) => Math.min(120, z + 10))} aria-label="Zoom in"><ZoomIn/></Button></div></div><div className="flex flex-1 items-start justify-center overflow-auto bg-document p-6"><img src={sampleDocument} alt="Sample historical land registry scan" loading="lazy" width={800} height={1200} className="h-auto shadow-document" style={{ width: `${zoom}%`, maxWidth: "720px" }}/></div></section>
      <section className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-semibold">Extracted record</h2><p className="mt-1 text-xs text-muted-foreground">Average confidence 87.8%</p></div><span className="rounded-full bg-warning-soft px-3 py-1 text-xs font-medium text-warning-foreground">2 fields need review</span></div><div className="grid gap-5 p-5 sm:grid-cols-2">{fields.map((field) => <div key={field.key} className={field.confidence < 75 ? "rounded-md border border-warning/30 bg-warning-soft p-3" : "p-3"}><div className="mb-2 flex items-end justify-between gap-2"><Label htmlFor={field.key} className="text-xs">{field.label}</Label><span className={`text-[10px] font-semibold ${field.confidence < 75 ? "text-warning-foreground" : "text-success"}`}>{field.confidence}%</span></div><Input id={field.key} value={field.value} onChange={(event) => setFields((items) => items.map((item) => item.key === field.key ? { ...item, value: event.target.value, confidence: 100 } : item))}/>{field.confidence < 75 && <p className="mt-2 flex items-center gap-1 text-[10px] text-warning-foreground"><AlertCircle className="size-3"/> Check against the scan</p>}</div>)}</div><div className="border-t border-border p-5"><h3 className="text-sm font-semibold">Validation preview</h3><div className="mt-3 space-y-2"><p className="flex items-center gap-2 text-xs text-success"><CheckCircle2 className="size-4"/> Mandatory fields are complete</p><p className="flex items-center gap-2 text-xs text-success"><CheckCircle2 className="size-4"/> Survey number pattern is valid</p><p className="flex items-center gap-2 text-xs text-muted-foreground"><FileText className="size-4"/> Duplicate check will run after submission</p></div></div></section></div>
  </div>;
}
